--G1_23BCS12759_ChandanSingla_Session1
CREATE TABLE EMPLOYEE(
EMP_ID INT,
EMP_NAME VARCHAR(20),
SALARY INT
)

INSERT INTO EMPLOYEE VALUES
(1,'CHANDAN',12000),
(2,'MADHAV',20000),
(3,'SHYAM',23000);

CREATE OR REPLACE VIEW EMPLOYEE_VIEW
AS
SELECT * FROM EMPLOYEE;

CREATE ROLE ANALYST 
WITH LOGIN PASSWORD '12759';

GRANT SELECT ON EMPLOYEE_VIEW TO ANALYST
