-- G1_23BCS12759_ChandanSingla_Session3
SELECT S.USER_ID, ROUND((SUM(CASE WHEN C.ACTION = 'confirmed' THEN 1 ELSE 0 END)::NUMERIC(5,2)/COUNT(*)),2)
AS CONFIRMATION_RATE
FROM SIGNUPS AS S
LEFT JOIN 
CONFIRMATIONS AS C
ON
S.USER_ID = C.USER_ID
GROUP BY S.USER_ID;
