# G1_23BCS12759_ChandanSingla_Session6 

(SELECT U.NAME as results FROM
USERS AS U 
JOIN
MOVIERATING AS M
on u.user_id = m.user_id
group by u.name
order by count(*) desc,u.name 
limit 1)
UNION ALL
(
SELECT M.TITLE FROM MOVIES AS M
JOIN 
MOVIERATING AS MR
ON
M.MOVIE_ID = MR.MOVIE_ID
WHERE EXTRACT(YEAR_MONTH FROM MR.CREATED_AT) = 202002
GROUP BY M.TITLE
ORDER BY AVG(MR.RATING) DESC,M.TITLE 
LIMIT 1
)
